spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: shop
    password: shop

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
